-- ============================================================
-- FILE: schema_ddl.sql
-- DESCRIPTION: Database initialization, drop scripts, and table creation
-- ============================================================

-- ------------------------------------------------------------
-- DROP TABLE STATEMENTS (To ensure a clean rebuild)
-- ------------------------------------------------------------
DROP TABLE Appointment_Medication       CASCADE CONSTRAINTS;
DROP TABLE Appointment_MedicalCondition CASCADE CONSTRAINTS;
DROP TABLE Appointment                  CASCADE CONSTRAINTS;
DROP TABLE Doctor                       CASCADE CONSTRAINTS;
DROP TABLE Patient                      CASCADE CONSTRAINTS;
DROP TABLE InsuranceProvider            CASCADE CONSTRAINTS;

-- ------------------------------------------------------------
-- TABLE INITIALIZATIONS & PHYSICAL CONSTRAINT RULES
-- ------------------------------------------------------------

CREATE TABLE InsuranceProvider (
    providerID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    providerName VARCHAR2(100) NOT NULL,
    contactNumber VARCHAR2(15)
);

CREATE TABLE Patient (
    patientID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(50) NOT NULL,
    lastName VARCHAR2(50) NOT NULL,
    dateOfBirth DATE NOT NULL,
    gender VARCHAR2(10),
    phoneNumber VARCHAR2(15),
    providerID INT,
    CONSTRAINT chk_gender CHECK (gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT fk_patient_insurance FOREIGN KEY (providerID) 
        REFERENCES InsuranceProvider(providerID) ON DELETE SET NULL
);

CREATE TABLE Doctor (
    doctorID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(50) NOT NULL,
    lastName VARCHAR2(50) NOT NULL,
    specialty VARCHAR2(100) NOT NULL,
    phoneNumber VARCHAR2(15)
);

CREATE TABLE Appointment (
    appointmentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patientID INT NOT NULL,
    doctorID INT NOT NULL,
    appointmentDate DATE NOT NULL,
    roomNumber INT NOT NULL,
    notes VARCHAR2(500),
    CONSTRAINT fk_app_patient FOREIGN KEY (patientID) REFERENCES Patient(patientID) ON DELETE CASCADE,
    CONSTRAINT fk_app_doctor FOREIGN KEY (doctorID) REFERENCES Doctor(doctorID) ON DELETE CASCADE
);

CREATE TABLE Appointment_MedicalCondition (
    appointmentID INT NOT NULL,
    conditionName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (appointmentID, conditionName),
    CONSTRAINT fk_cond_app FOREIGN KEY (appointmentID) REFERENCES Appointment(appointmentID) ON DELETE CASCADE
);

CREATE TABLE Appointment_Medication (
    appointmentID INT NOT NULL,
    medicationName VARCHAR2(100) NOT NULL,
    dosage VARCHAR2(50),
    PRIMARY KEY (appointmentID, medicationName),
    CONSTRAINT fk_med_app FOREIGN KEY (appointmentID) REFERENCES Appointment(appointmentID) ON DELETE CASCADE
);